env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3

script: "bundle exec rake"

gemfile:
  - Gemfile

before_install:
  - uname -a
  - sudo apt-get update
  - sudo apt-get install libvips-dev

