sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - VIPS_VERSION_MAJOR=8
    - VIPS_VERSION_MINOR=5
    - VIPS_VERSION_MICRO=3
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
    - PYTHONPATH=$HOME/vips/lib/python2.7/site-packages:$PYTHONPATH
    - GI_TYPELIB_PATH=$HOME/vips/lib/girepository-1.0:$GI_TYPELIB_PATH

dist: trusty

addons:
  apt:
    packages:
      - libxml2-dev
      - gettext
      - python-dev
      - liblcms1-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev
      - libglib2.0-dev

cache:
  directories:
    - $HOME/vips

# gobject-introspection 3.1 declares itself as 2.1 minimum, so we can't test
# 2.0 ... in fact it seems to work if you force it, but I don't think we can do
# that on travis
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

script: "bundle exec rake"

gemfile:
  - Gemfile

before_install:
  - uname -a
  - bash install-vips.sh
